/********************************************************************
* ./src/LAPPDRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/LAPPDRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLAPPDRootDict();
extern void G__cpp_setup_inheritanceLAPPDRootDict();
extern void G__cpp_setup_typetableLAPPDRootDict();
extern void G__cpp_setup_memvarLAPPDRootDict();
extern void G__cpp_setup_globalLAPPDRootDict();
extern void G__cpp_setup_memfuncLAPPDRootDict();
extern void G__cpp_setup_funcLAPPDRootDict();
extern void G__set_cpp_environmentLAPPDRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LAPPDpulse.hh"
#include "LAPPDpulseCluster.hh"
#include "LAPPDresponse.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LAPPDRootDictLN_TClass;
extern G__linked_taginfo G__LAPPDRootDictLN_TBuffer;
extern G__linked_taginfo G__LAPPDRootDictLN_TMemberInspector;
extern G__linked_taginfo G__LAPPDRootDictLN_TObject;
extern G__linked_taginfo G__LAPPDRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LAPPDRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LAPPDRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LAPPDRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LAPPDRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LAPPDRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LAPPDRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LAPPDRootDictLN_TH1D;
extern G__linked_taginfo G__LAPPDRootDictLN_LAPPDpulse;
extern G__linked_taginfo G__LAPPDRootDictLN_LAPPDpulseCluster;
extern G__linked_taginfo G__LAPPDRootDictLN_vectorlELAPPDpulsemUcOallocatorlELAPPDpulsemUgRsPgR;
extern G__linked_taginfo G__LAPPDRootDictLN_reverse_iteratorlEvectorlELAPPDpulsemUcOallocatorlELAPPDpulsemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LAPPDRootDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LAPPDRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LAPPDRootDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__LAPPDRootDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LAPPDRootDictLN_TRandom3;
extern G__linked_taginfo G__LAPPDRootDictLN_LAPPDresponse;

/* STUB derived class for protected member access */
